-- ============================================================================
-- Remove the eight unsourced Jaguar / Land Rover MSRP rows.
--
-- Vic, 2026-09-12: "yes purge the jaguar and land rover rows".
--
-- WHY THEY GO. Two independent reasons, either of which is sufficient.
--
-- 1. THEY FAIL OUR OWN PUBLISHING STANDARD. Every one of the eight carries
--    source_url NULL and price_basis NULL. No source a buyer can re-check, no
--    statement of whether the figure includes freight. msrp-100-percent-accuracy
--    is explicit: a known basis, a pinned configuration and a dated capture, or
--    we do not publish. These have none of the three. They were hand-typed from
--    GuideAutoWeb — a third party, not the manufacturer — and that origin
--    survives only in a SQL comment, invisible to the app and to every report.
--
-- 2. THEY ARE WRONG TODAY, AND WRONG IN THE DIRECTION THAT ACCUSES A DEALER.
--    Checked against the manufacturer on 2026-09-12:
--
--      model              our row    manufacturer    error
--      Discovery           79,900        87,000      understated  7,100
--      Defender            74,100        77,100      understated  3,000
--      Range Rover Velar   69,500        71,500      understated  2,000
--      Range Rover        133,000       130,200      overstated   2,800
--      Discovery Sport     59,800        65,460      see note below
--
--    An UNDERSTATED MSRP inflates apparent dealer markup. Three of these would
--    have had LotCheck tell a buyer a dealer was asking further over sticker
--    than they were — a false claim about a named business, generated by us,
--    from a number with no source. That is the exposure shape in
--    [[ai-defamation-entity-match-lesson]], and it is live in production until
--    this runs.
--
--    (Discovery Sport is worse than a simple error: 59,800 matches the config
--    API's PRE-FREIGHT base while the manufacturer's own page shows 65,460
--    all-in. The row does not say which basis it is, so it cannot be compared
--    to an Alberta all-in advertised price at all. market-read-window-basis.)
--
--    The Jaguar row is doubly wrong: $67,000 is the f-pace_k255 2025.5 price,
--    stamped as a 2026 MSRP.
--
-- THE FULL CONTENTS, RECORDED HERE SO DELETING THEM LOSES NOTHING:
--
--   id   year  make         model                msrp     basis  source_url
--   1474 2026  Land Rover   Range Rover         133,000   NULL   NULL
--   1475 2026  Land Rover   Range Rover Sport    94,950   NULL   NULL
--   1476 2026  Land Rover   Range Rover Velar    69,500   NULL   NULL
--   1477 2026  Land Rover   Range Rover Evoque   57,600   NULL   NULL
--   1478 2026  Land Rover   Defender             74,100   NULL   NULL
--   1479 2026  Land Rover   Discovery            79,900   NULL   NULL
--   1480 2026  Land Rover   Discovery Sport      59,800   NULL   NULL
--   1481 2026  Jaguar       F-PACE               67,000   NULL   NULL
--   all fetched_at 2026-08-08, untouched since.
--
-- WHAT THE PRODUCT DOES AFTERWARDS, and why that is better than this.
--
-- Jaguar and Land Rover join Audi, Tesla and Polestar: makes the product can
-- encounter with NO MSRP denominator at all. The daily MSRP report already
-- handles that state explicitly — they move out of "NEVER REFRESHED" and into
-- "NO DENOMINATOR AT ALL — makes the product can encounter hold ZERO rows",
-- which is exactly what will be true. A used JLR listing will make no
-- MSRP-vs-asking claim rather than a wrong one. Missing beats wrong.
--
-- WHY THIS IS NOT A SCRAPER PROBLEM. Land Rover's only correct MSRP source is
-- rules.config.landrover.com, whose robots.txt is "User-agent: *" /
-- "Disallow: /" (read 2026-09-12). The robots-clean alternative mixes price
-- bases inside a single page — Range Rover Sport SV differs by $18,092 between
-- the two — so scraping it would reproduce exactly the basis confusion that
-- makes the Discovery Sport row unusable. Jaguar publishes no robots-clean
-- priced surface at all. Building a scraper is a legal decision, not an
-- engineering one, and it is Vic's. [[aggregator-scraping-tos]]
--
-- A REBUILD FROM MIGRATIONS STAYS CORRECT. 20260808_euro_british_msrp_catalog
-- re-inserts these rows, and this file sorts after it (20260912b > 20260808),
-- so replaying every migration in order ends with them absent. The seed is left
-- untouched on purpose: it is the historical record of what was believed on
-- 2026-08-08, and rewriting history to hide a mistake is how the mistake gets
-- made again. [[fixing-history-log]]
--
-- Paste into the Supabase SQL editor. Safe to re-run.
-- ============================================================================

-- ---- 1) show exactly what is about to go, before it goes -------------------
-- "Success. No rows returned" has twice this month meant nothing happened. This
-- prints the rows first, so the editor shows what was removed and not just that
-- something was.
do $$
declare r record; n integer := 0;
begin
  raise notice 'About to delete these rows from msrp_catalog:';
  for r in
    select id, year, make, model, msrp, source_url
      from public.msrp_catalog
     where make in ('Jaguar', 'Land Rover')
     order by make, model
  loop
    n := n + 1;
    raise notice '  id=% % % % $% source_url=%',
      r.id, r.year, r.make, r.model, r.msrp, coalesce(r.source_url, '(none)');
  end loop;
  if n = 0 then
    raise notice '  (none found — already purged, or never present)';
  else
    raise notice '% row(s) will be deleted.', n;
  end if;
end $$;

-- ---- 2) the delete ---------------------------------------------------------
-- Scoped to rows with NO source_url. If a real scraper ever lands for these
-- makes, its rows WILL carry a source and this migration would not touch them
-- on a re-run — so re-running after a future build cannot wipe good data.
delete from public.msrp_catalog
 where make in ('Jaguar', 'Land Rover')
   and (source_url is null or btrim(source_url) = '');

-- ---- 3) prove it ------------------------------------------------------------
do $$
declare n integer;
begin
  select count(*) into n
    from public.msrp_catalog
   where make in ('Jaguar', 'Land Rover')
     and (source_url is null or btrim(source_url) = '');
  if n <> 0 then
    raise exception 'expected 0 unsourced Jaguar/Land Rover rows, found %', n;
  end if;

  select count(*) into n from public.msrp_catalog where make in ('Jaguar', 'Land Rover');
  raise notice 'OK: no unsourced Jaguar/Land Rover rows remain. % sourced row(s) still present.', n;
  raise notice 'These makes now hold no MSRP denominator, which the daily MSRP report states explicitly.';
end $$;
